import type { BrowserCookieItem, CookieFormData } from './browserCookies';
import { parseImportedCookies } from './browserCookies';

export type CookieImportFormat = 'json' | 'netscape' | 'header';

const NETSCAPE_HEADER = '# Netscape HTTP Cookie File';

export function detectCookieImportFormat(text: string): CookieImportFormat {
  const trimmed = text.trim();
  if (!trimmed) {
    throw new Error('Empty content');
  }
  if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
    return 'json';
  }
  if (trimmed.startsWith('# Netscape') || trimmed.includes('\t')) {
    const dataLine = trimmed.split('\n').find(line => line.trim() && !line.startsWith('#'));
    if (dataLine && dataLine.split('\t').length >= 7) {
      return 'netscape';
    }
  }
  return 'header';
}

export function serializeNetscape(cookies: BrowserCookieItem[]): string {
  const lines = [
    NETSCAPE_HEADER,
    '# https://curl.se/docs/http-cookies.html',
    '# This file was generated by sync-your-cookie.',
    '',
  ];
  for (const cookie of cookies) {
    const hostOnly = cookie.hostOnly ?? !cookie.domain.startsWith('.');
    const domain = hostOnly
      ? cookie.domain.replace(/^\./, '')
      : cookie.domain.startsWith('.')
        ? cookie.domain
        : `.${cookie.domain}`;
    const includeSubdomains = hostOnly ? 'FALSE' : 'TRUE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiration =
      cookie.session || cookie.expirationDate == null ? '0' : String(Math.floor(cookie.expirationDate));
    lines.push(
      [domain, includeSubdomains, cookie.path || '/', secure, expiration, cookie.name, cookie.value].join('\t'),
    );
  }
  return lines.join('\n');
}

export function parseNetscape(text: string): Partial<CookieFormData>[] {
  const items: Partial<CookieFormData>[] = [];
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const parts = trimmed.split('\t');
    if (parts.length < 7) continue;
    const [domainRaw, includeSubdomains, path, secure, expiration, name, ...valueParts] = parts;
    const value = valueParts.join('\t');
    const hostOnly = includeSubdomains.toUpperCase() === 'FALSE';
    const domain = hostOnly ? domainRaw.replace(/^\./, '') : domainRaw.startsWith('.') ? domainRaw : `.${domainRaw}`;
    items.push({
      name,
      value,
      domain,
      path: path || '/',
      expirationDate: expiration === '0' || !expiration ? null : Number(expiration),
      secure: secure.toUpperCase() === 'TRUE',
      httpOnly: false,
      sameSite: 'unspecified',
    });
  }
  return items;
}

export function serializeHeaderString(cookies: BrowserCookieItem[]): string {
  return cookies
    .filter(cookie => cookie.name)
    .map(cookie => `${cookie.name}=${cookie.value}`)
    .join('; ');
}

export function parseHeaderString(text: string): Partial<CookieFormData>[] {
  let content = text.trim();
  if (content.toLowerCase().startsWith('cookie:')) {
    content = content.slice('cookie:'.length).trim();
  }
  const items: Partial<CookieFormData>[] = [];
  for (const part of content.split(';')) {
    const trimmed = part.trim();
    if (!trimmed) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex <= 0) continue;
    items.push({
      name: trimmed.slice(0, eqIndex).trim(),
      value: trimmed.slice(eqIndex + 1).trim(),
      path: '/',
      secure: false,
      httpOnly: false,
      sameSite: 'unspecified',
    });
  }
  return items;
}

export function parseCookieImport(text: string, defaultDomain: string): Partial<CookieFormData>[] {
  const format = detectCookieImportFormat(text);
  let items: Partial<CookieFormData>[] = [];
  switch (format) {
    case 'json':
      items = parseImportedCookies(text);
      break;
    case 'netscape':
      items = parseNetscape(text);
      break;
    case 'header':
      items = parseHeaderString(text);
      break;
  }
  return items.map(item => ({
    ...item,
    domain: item.domain || defaultDomain,
  }));
}
